### ISSUE TITLE
How might one add claim/permission/role validation to the JWT middleware?

### ISSUE THREAD

**Issue by MichaelBonnet** [zett-8/go-clean-echo#1]
I want to be able to validate specific roles and permissions depending on the endpoint being hit. How might I do that, using the middleware example in the repo?

**Comment by zett-8** [comment]
@MichaelBonnet 

I think so.
JWT authentication in this repository closely resembles the actions taken for roles and permissions validation.
Additionally, from what I understand, it's generally best practice to handle these actions (validation and authentication) in middleware.
